"use client";

import { useEffect, useRef, useState, type ReactNode } from "react";

/* Security-paper pieces: the page is dressed like a banknote or a cheque, so sections open on a
   numbered ledger rule instead of a badge, rules carry microprint, and status lands as a rubber stamp.
   Styles in app/paper.css (pp-*); the guilloché art is generated by scripts/paper-art.mjs. */

/** A line of tiny repeated text, like the microprint on a note's border. Decorative. */
export function Microprint({ text = "VERTLO · ONE ACCOUNT CLOSES · THE REST KEEP SELLING · ", className }: { text?: string; className?: string }) {
  return (
    <span className={className ? `pp-micro ${className}` : "pp-micro"} aria-hidden="true">
      {text.repeat(12)}
    </span>
  );
}

/** A section's opening rule: its serial number and name on a hairline, microprint running out to the edge. */
export function SectionRule({ no, children }: { no: string; children: ReactNode }) {
  return (
    <div className="pp-rule">
      <span className="pp-rule-no">Nº {no}</span>
      <span className="pp-rule-label">{children}</span>
      <Microprint />
    </div>
  );
}

/** A rubber stamp: double-ruled capitals, a little tilted, inked with grain. Pressed in when it scrolls into view. */
export function Stamp({ children, tone = "ink", className }: { children: ReactNode; tone?: "ink" | "red" | "mint"; className?: string }) {
  const ref = useRef<HTMLSpanElement>(null);
  // Until hydration the stamp is simply there; once JS runs it waits for the viewport, then presses in once.
  const [state, setState] = useState<"idle" | "wait" | "in">("idle");
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    setState("wait");
    const io = new IntersectionObserver(
      ([e]) => {
        if (!e.isIntersecting) return;
        setState("in");
        io.disconnect();
      },
      { threshold: 0.6 },
    );
    io.observe(el);
    return () => io.disconnect();
  }, []);
  return (
    <span
      ref={ref}
      className={`pp-stamp pp-stamp--${tone}${className ? ` ${className}` : ""}`}
      data-state={state === "idle" ? undefined : state}
      aria-hidden="true"
    >
      <span>{children}</span>
    </span>
  );
}
