"use client";

import { useEffect, useRef, useState, type ReactNode } from "react";
import { sheets, type SheetId } from "@/content/landing";

/* Security-paper pieces: the page is a desk of financial papers, so each section is a sheet with a
   printed document header instead of a badge, rules carry microprint, and status lands as a rubber stamp.
   Styles in app/paper.css (pp-*); the guilloché art is generated by scripts/paper-art.mjs. */

/** A line of tiny repeated text, like the microprint on a note's border. Decorative. */
export function Microprint({ text = "VERTLO · ONE ACCOUNT CLOSES · THE REST KEEP SELLING · ", className }: { text?: string; className?: string }) {
  return (
    <span className={className ? `pp-micro ${className}` : "pp-micro"} aria-hidden="true">
      {text.repeat(12)}
    </span>
  );
}

const pad = (n: number) => String(n).padStart(2, "0");

/**
 * One document in the stack. The section is the sticky layer (its offset comes from PaperMotion, which
 * measures the sheet so a tall one sticks by its bottom edge); the tilt and paper layers inside take
 * the scroll motion. Printed along the top: the document's title, microprint, its form code and its
 * place in the stack. `bare` drops the paper and header for a sheet that is its own document (the cheque).
 */
export function Sheet({
  id,
  anchor,
  tone,
  bare,
  children,
}: {
  id: SheetId;
  anchor?: string;
  tone?: "dark";
  bare?: boolean;
  children: ReactNode;
}) {
  const i = sheets.findIndex((s) => s.id === id);
  const s = sheets[i];
  return (
    <section
      id={anchor}
      className={`pp-sheet pp-sheet--${id}${tone === "dark" ? " vt-bleed" : ""}${bare ? " pp-sheet--bare" : ""}`}
      data-sheet={id}
      data-title={s.doc}
      data-n={i + 1}
      style={{ zIndex: i + 1 }}
    >
      <div className="pp-sheet-tilt">
        <div className="pp-sheet-paper">
          {bare ? null : (
            <header className="pp-doc">
              <span className="pp-doc-title">{s.doc}</span>
              <Microprint />
              <span className="pp-doc-meta">
                {s.form}
                <b>
                  Sheet {pad(i + 1)} of {pad(sheets.length)}
                </b>
              </span>
            </header>
          )}
          {children}
          <span className="pp-sheet-shade" aria-hidden="true" />
        </div>
      </div>
    </section>
  );
}

/** A rubber stamp: double-ruled capitals, a little tilted, inked with grain. Pressed in when it scrolls into view. */
export function Stamp({ children, tone = "ink", className }: { children: ReactNode; tone?: "ink" | "red" | "mint"; className?: string }) {
  const ref = useRef<HTMLSpanElement>(null);
  // Until hydration the stamp is simply there; once JS runs it waits for the viewport, then presses in once.
  const [state, setState] = useState<"idle" | "wait" | "in">("idle");
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    setState("wait");
    const io = new IntersectionObserver(
      ([e]) => {
        if (!e.isIntersecting) return;
        setState("in");
        io.disconnect();
      },
      { threshold: 0.6 },
    );
    io.observe(el);
    return () => io.disconnect();
  }, []);
  return (
    <span
      ref={ref}
      className={`pp-stamp pp-stamp--${tone}${className ? ` ${className}` : ""}`}
      data-state={state === "idle" ? undefined : state}
      aria-hidden="true"
    >
      <span>{children}</span>
    </span>
  );
}
