"use client";

import { useEffect, useRef, useState, type CSSProperties, type ReactNode } from "react";
import { Diamond } from "@/components/vertlo";
import { sheets, type Letter as LetterContent, type SheetId } from "@/content/landing";

/* Security-paper pieces: the page is a desk of financial papers, so each section is a sheet with a
   printed document header instead of a badge, typed letters carry the story, microprint runs on the
   note, and status lands as a rubber stamp. Styles in app/paper.css (pp-*); the guilloché art is
   generated by scripts/paper-art.mjs. */

/** A line of tiny repeated text, like the microprint on a note's border. Decorative. */
export function Microprint({ text, className }: { text: string; className?: string }) {
  return (
    <span className={className ? `pp-micro ${className}` : "pp-micro"} aria-hidden="true">
      {text.repeat(16)}
    </span>
  );
}

const pad = (n: number) => String(n).padStart(2, "0");

/**
 * One document in the stack. The section is the sticky layer (its offset comes from PaperMotion, which
 * measures the sheet so a tall one sticks by its bottom edge); the tilt and paper layers inside take
 * the scroll motion. Printed along the top: the document's title, the date it belongs to in the story,
 * and its place in the stack. `bare` drops the paper and header for a sheet that is its own document
 * (the cheque).
 */
export function Sheet({ id, anchor, bare, children }: { id: SheetId; anchor?: string; bare?: boolean; children: ReactNode }) {
  const i = sheets.findIndex((s) => s.id === id);
  const s = sheets[i];
  return (
    <section
      id={anchor}
      className={`pp-sheet pp-sheet--${id}${bare ? " pp-sheet--bare" : ""}`}
      data-sheet={id}
      data-title={s.doc}
      data-n={i + 1}
      style={{ zIndex: i + 1 }}
    >
      <div className="pp-sheet-tilt">
        <div className="pp-sheet-paper">
          {bare ? null : (
            <header className="pp-doc">
              <span className="pp-doc-title">{s.doc}</span>
              <span className="pp-doc-meta">
                {s.date}
                <b>
                  {pad(i + 1)} / {pad(sheets.length)}
                </b>
              </span>
            </header>
          )}
          {children}
          <span className="pp-sheet-shade" aria-hidden="true" />
        </div>
      </div>
    </section>
  );
}

/**
 * A typed letter: letterhead, reference, body, signature, then an optional note typed under it and a
 * stamp. Lines marked `strike` are struck through once they have typed on (PaperMotion drives both).
 * `tilt` is how far the sheet of letter paper sits off square, in degrees.
 */
export function Letter({ letter, tilt = -1 }: { letter: LetterContent; tilt?: number }) {
  return (
    <article className="pp-letter" aria-label={letter.label} style={{ "--tilt": `${tilt}deg` } as CSSProperties}>
      <header className="pp-letter-head">
        <span>
          <b>{letter.from}</b>
          {letter.fromSub}
        </span>
        <span>{letter.date}</span>
      </header>
      <p className="pp-letter-ref">{letter.ref}</p>
      {letter.lines.map((l, i) => (
        <p key={i} className="pp-letter-line">
          {l.strike ? <del>{l.text}</del> : l.text}
        </p>
      ))}
      <p className="pp-letter-sign">{letter.sign}</p>
      {letter.note ? (
        <p className="pp-letter-note">
          <Diamond size={7} />
          <span>
            <b>{letter.note.at}</b> {letter.note.text}
          </span>
        </p>
      ) : null}
      <Stamp className="pp-letter-stamp">{letter.stamp}</Stamp>
      <span className="pp-illus">{letter.label}</span>
    </article>
  );
}

/** A rubber stamp: double-ruled capitals, a little tilted, inked with grain. Pressed in when it scrolls into view. */
export function Stamp({ children, tone = "ink", className }: { children: ReactNode; tone?: "ink" | "red" | "mint"; className?: string }) {
  const ref = useRef<HTMLSpanElement>(null);
  // Until hydration the stamp is simply there; once JS runs it waits for the viewport, then presses in once.
  const [state, setState] = useState<"idle" | "wait" | "in">("idle");
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    setState("wait");
    const io = new IntersectionObserver(
      ([e]) => {
        if (!e.isIntersecting) return;
        setState("in");
        io.disconnect();
      },
      { threshold: 0.6 },
    );
    io.observe(el);
    return () => io.disconnect();
  }, []);
  return (
    <span
      ref={ref}
      className={`pp-stamp pp-stamp--${tone}${className ? ` ${className}` : ""}`}
      data-state={state === "idle" ? undefined : state}
      aria-hidden="true"
    >
      <span>{children}</span>
    </span>
  );
}
