import type { ReactElement } from "react";
import type * as T from "./types";
import * as L from "./lib";

export type * from "./types";

export const ProviderFlow = L.ProviderFlow as unknown as (p: T.ProviderFlowProps) => ReactElement;
export const FeatureGrid = L.FeatureGrid as unknown as (p: T.FeatureGridProps) => ReactElement;
export const PixelArt = L.PixelArt as unknown as (p: T.PixelArtProps) => ReactElement;
export const IndustryCards = L.IndustryCards as unknown as (p: T.IndustryCardsProps) => ReactElement;
export const FeatureStrip = L.FeatureStrip as unknown as (p: T.FeatureStripProps) => ReactElement;
export const Figure = L.Figure as unknown as (p: T.FigureProps) => ReactElement;
export const LineField = L.LineField as unknown as (p: { seed?: number; count?: number; className?: string }) => ReactElement;
export const Portal = L.Portal as unknown as (p: T.PortalProps) => ReactElement;
export const PortalStage = L.PortalStage as unknown as (p: T.PortalStageProps) => ReactElement;
export const CrmSlice = L.CrmSlice as unknown as (p: T.CrmSliceProps) => ReactElement;
export const ProductCard = L.ProductCard as unknown as (p: T.ProductCardProps) => ReactElement;
export const Button = L.Button as unknown as (p: T.ButtonProps) => ReactElement;
export const Pill = L.Pill as unknown as (p: T.PillProps) => ReactElement;
export const PillInput = L.PillInput as unknown as (p: T.PillInputProps) => ReactElement;
export const Icon = L.Icon as unknown as (p: T.IconProps) => ReactElement;
export const Diamond = L.Diamond as unknown as (p: T.DiamondProps) => ReactElement;
export const Logo = L.Logo as unknown as (p: T.LogoProps) => ReactElement;
export const StealthPanel = L.StealthPanel as unknown as (p: T.StealthPanelProps) => ReactElement;
export const OrbitArt = L.OrbitArt as unknown as (p: T.OrbitArtProps) => ReactElement;
export const CountUp = L.CountUp as unknown as (p: T.CountUpProps) => ReactElement;
export const RotatingWord = L.RotatingWord as unknown as (p: T.RotatingWordProps) => ReactElement;
export const Nav = L.Nav as unknown as (p: T.NavProps) => ReactElement;
export const Hero = L.Hero as unknown as (p: T.HeroProps) => ReactElement;
export const LineArtCard = L.LineArtCard as unknown as (p: T.LineArtCardProps) => ReactElement;
export const PlanCard = L.PlanCard as unknown as (p: T.PlanCardProps) => ReactElement;
export const StatCard = L.StatCard as unknown as (p: T.StatCardProps) => ReactElement;
export const FeaturePanel = L.FeaturePanel as unknown as (p: T.FeaturePanelProps) => ReactElement;
export const Notification = L.Notification as unknown as (p: T.NotificationProps) => ReactElement;
export const NotificationStack = L.NotificationStack as unknown as (p: T.NotificationStackProps) => ReactElement;
export const HowItWorks = L.HowItWorks as unknown as (p: T.HowItWorksProps) => ReactElement;
export const LogoStrip = L.LogoStrip as unknown as (p: T.LogoStripProps) => ReactElement;
export const Testimonial = L.Testimonial as unknown as (p: T.TestimonialProps) => ReactElement;
export const FAQ = L.FAQ as unknown as (p: T.FAQProps) => ReactElement;
export const CTABand = L.CTABand as unknown as (p: T.CTABandProps) => ReactElement;
export const Footer = L.Footer as unknown as (p: T.FooterProps) => ReactElement;
